// Author api Routes
  


  // Creation Process
    ###
post http://localhost:4000/author-api/user
Content-Type: application/json
      
         {
               "userType":"author",
                "username":"Abhii",
                "password":"Abhiiii",
                "email":"Abbii@gmail.com"
         }  
        
     // login Process
###
post http://localhost:4000/author-api/login
Content-Type: application/json
    
         {
              "userType":"author",
              "username":"Abhii",
              "password":"Abhiiii"
                      
     }


### add new article by author
post http://localhost:4000/author-api/add-article
Content-Type: application/json

{
   "articleId":"{{$timestamp}}",
   "title":"C &C++",
   "category":"Progrming",
   "content":"  Ready to unlock your dream job? Let FlowCV lead the way. Curate stunning resumes, get invaluable feedback, and share your story with the world. Your next big career move starts now.",
   "dateOfCreation":"{{$datetime iso8601}}",
   "dateOfModification":"{{$datetime iso8601}}",
   "username":"Abhi",
   "comments": [ ],
   "status":true
   
}


// get all articles
###
get http://localhost:4000/author-api/articles/abhii




      // Modified the article
###  
put http://localhost:4000/author-api/article
Content-Type: application/json

{
   
   "articleId":"1738852659",
   "title":"C",
   "category":"Progrming",
   "content":"Ready to unlock your dream job? 1734273537' ",
   "dateOfCreation":"2024-12-15T13:03:49.899Z",
   "dateOfModification":"{{$datetime iso8601}}",
   "username":"Abhi",
   "comments": [ ],
   "status":true
   
}

// soft delete an article by a aritcleId'
###

### soft delete an article by article id
put http://localhost:4000/author-api/article/1741857877621
Content-Type: application/json

{
   "articleId":"1741857877621",
   "title":"Fundamentals of JavaScript",
   "category":"programming",
   "content":"JavaScript is a high-level programming language that follows the ECMAScript standard. It was originally designed as a scripting language for websites but became widely adopted as a general-purpose programming language, and is currently the most popular programming language in use.[1] JavaScript is usually found running in a web browser as interactive or automated content, ranging from popup messages and live clocks to large web applications. JavaScript is also commonly used in server-side programming through platforms",
   "dateOfCreation":"2024-02-26T13:56:22.487Z",
   "dateOfModification":"{{$datetime iso8601}}",
   "username":"vikas",
   "comments": [ ],
   "status":true
   
}


###
GET http://localhost:4000/author-api/profile/Pallikonda21


