 // ### user Api requests

### 
post http://localhost:4000/user-api/user
Content-Type: application/json

      {
         "userType": "user",
         "username":"Addhitya",
         "password":"Aditya",
          "email":"Adi256@gail.com"
      }  

###
post http://localhost:4000/user-api/login
Content-Type:application/json
{
                   "userType":"user",
                   "username":"Aditya",
                   "password":"Aditya"
            
              }
 
   
###reading articles of all users
get http://localhost:4000/user-api/articles


### write comment
post http://localhost:4000/user-api/comment/1742467701156
Content-Type: application/json

{
   
    "username":"Pallikonda21",
    "comment":"ary srikanth em chepauv ra"
   
}